### ISSUE TITLE
Arazo bat egon da

### ISSUE THREAD

**Issue by mirenbz** [garazilasa/garazilasa.github.io#6]
Kaixo @garazilasa , ohartu bazara, zure webgunea bistaratzerakoan, ez da post-a agertzen. Dirudienez, webgunea ez da ari behar bezala sortzen (baliteke GitHub-etik email bat jaso izana hau jakinaraziz). Seguruenik `_config.yml` artxiboaren 5. lerroarengatik izan daiteke:

https://github.com/garazilasa/github-pages/blob/2e99ad9c117caa5f8faec5384405e59ea3e81ac2/_config.yml#L5

Lerro horrek bi espazio hutsekin hasi beharra dauka. Editatu ezazu bi espazio horiek gehitzeko, eta ea webgunea behar bezala eratzen den.

**Comment by garazilasa** [comment]
konpondua

**Comment by mirenbz** [comment]
Bai! Oso ondo. #5-ean jarraituko dugu, eta hau itxi egingo dut.
